# Generated by Django 4.1.2 on 2022-10-10 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_alter_hashtag_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hashtag',
            table='hashtags',
        ),
    ]
