# Generated by Django 4.1.2 on 2022-10-10 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0006_rename_hashtag_id_tweet_hashtag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='hastag',
            new_name='hashtag',
        ),
    ]
