# Generated by Django 4.1.3 on 2022-11-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0010_tweet_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='sentiment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='sentiment_score',
            field=models.FloatField(null=True),
        ),
    ]
