# Generated by Django 4.1.2 on 2022-10-10 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hashtag',
            table='hashtag',
        ),
    ]
