# Generated by Django 4.1.2 on 2022-10-10 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.IntegerField(unique=True)),
                ('content', models.CharField(max_length=280)),
                ('user_mentions_count', models.IntegerField()),
                ('favorite_count', models.IntegerField()),
                ('retweet_count', models.IntegerField()),
                ('hashtag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudapp.hashtag')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudapp.user')),
            ],
            options={
                'db_table': 'tweets',
            },
        ),
    ]
