# Generated by Django 4.1.2 on 2022-10-10 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0005_user_status_count_alter_user_name_alter_user_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='hashtag_id',
            new_name='hashtag',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='user_id',
            new_name='user',
        ),
    ]
