# Generated by Django 4.1.2 on 2022-10-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0008_alter_tweet_tweet_id_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
