# Generated by Django 4.1.3 on 2022-11-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0012_tweet_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
    ]
